/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.EOFException;
import java.io.File;
import java.io.IOException;
import java.net.SocketException;

/**
 *
 * @author near
 */
public class DocumentsDialogBox extends javax.swing.JDialog {

    /**
     * Creates new form ListDialogBox
     */
    public DocumentsDialogBox(java.awt.Frame parent, boolean modal, String status, java.util.List<String> result) {
        super(parent, modal);
        this.status = status;
        this.result = result;
        initComponents();
        render();
        addActionListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        jTable1.setSelectionBackground(null);
        jTable1.setSelectionForeground(null);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STATUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1243, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pack();
    }

    private void render(){
        jLabel2.setText(status);
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(model);
        model.addColumn("Applicant ID");
        model.addColumn("Enrollment Form");
        model.addColumn("Entrance MarkSheet");
        model.addColumn("HSC MarkSheet");

            for(int i=0;i<result.size();i++){
                String id = result.get(i);
                model.insertRow(i,new Object[]{id,"","",""});
            }
    }

    private void addActionListeners(){
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jTable1.rowAtPoint(e.getPoint());
                int col = jTable1.columnAtPoint(e.getPoint());
                String id = (String) jTable1.getValueAt(row,0);
                if(col == 1)
                    getFile(id,"_form.pdf");
                else if(col == 2)
                    getFile(id,"_entrance.pdf");
                else if(col == 3)
                    getFile(id,"_hsc.pdf");
            }
        });
    }

    private void getFile(String applicantId,String suffix){
        try{
            Main.dataOutputStream.writeInt(2);
            Main.dataOutputStream.writeUTF(applicantId+suffix);
            int status = Main.dataInputStream.readInt();
            if(status>=200 && status<=299){
                // read extension
                Main.dataInputStream.readUTF();
                Main.receiveFile("downloads/"+applicantId+suffix);
                if (Desktop.isDesktopSupported()) {
                    try {
                        File myFile = new File( "downloads/"+applicantId+suffix);
                        Desktop.getDesktop().open(myFile);
                    } catch (IOException ex) {
                        String message = "Saved to downloads/"+applicantId+suffix;
                        Dialog dialog = new DialogBox(Main.frame,true,message);
                        dialog.setLocationRelativeTo(Main.frame);
                        dialog.setVisible(true);
                    }
                }
            }else{
                String message = "Signature for "+applicantId+" Not Found";
                Dialog dialog = new DialogBox(Main.frame,true,message);
                dialog.setLocationRelativeTo(Main.frame);
                dialog.setVisible(true);
            }
        }catch (SocketException | EOFException exception) {
            Main.raiseErrorPage(new ErrorPage(500,exception));
        }catch (Exception exception){
            Main.raiseErrorPage(new ErrorPage(exception));
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private String status;
    private DefaultTableModel model;
    private java.util.List<String> result;
    // End of variables declaration
}
